---
name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use pyinstall to create distribution binary
      run: pyinstaller -F support_bundle_bootstrap.py
    - name: version
      run: echo "version=$(./dist/support_bundle -v)" >> $GITHUB_ENV
      id: version
      
    - name: Tar bootstrap
      # tar with previous distibuted name for backwards compatibility
      run: cd dist; mv support_bundle_bootstrap vm-support-bundle; tar -zcvf support_bundle_bootstrap.tar.gz vm-support-bundle
    - name: Tar main script  
      run: cd dist; mv support_bundle .support_bundle; tar cfvz support_bundle.tar.gz .support_bundle
    - name: release
      uses: actions/create-release@v1
      id: release
      with:
        draft: false
        prerelease: false
        release_name: v${{ env.version }}
        tag_name: v${{ env.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload support_bundle bootstrap release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/support_bundle_bootstrap.tar.gz
        asset_name: support_bundle_bootstrap.tar.gz
        asset_content_type: application/gzip

    - name: Upload support_bundle release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/support_bundle.tar.gz
        asset_name: support_bundle.tar.gz
        asset_content_type: application/gzip
