---
name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # this is just the host, but the job will run in the container
    container: ubuntu:20.04
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        # Install required dependencies inside the container
        apt-get update
        apt-get install -y python3 python3-pip python3-dev wget build-essential
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use pyinstall to create distribution binary
      run: mkdir /opt/netfoundry; pyinstaller -F support_bundle_bootstrap.py --runtime-tmpdir /opt/netfoundry/
    - name: version
      run: echo "version=$(./dist/support_bundle -v)" >> $GITHUB_ENV
      id: version
      
    - name: Tar bootstrap
      # tar with previous distibuted name for backwards compatibility
      run: cd dist; mv support_bundle_bootstrap vm-support-bundle; tar -zcvf support_bundle_bootstrap.tar.gz vm-support-bundle
    - name: Tar main script  
      run: cd dist; mv support_bundle .support_bundle; tar cfvz support_bundle.tar.gz .support_bundle

    - name: release
      uses: ncipollo/release-action@v1
      id: release
      with:
        draft: false
        prerelease: false
        tag: v${{ env.version }}
        artifacts: "dist/support_bundle_bootstrap.tar.gz,dist/support_bundle.tar.gz"
        artifactContentType: application/gzip
      env:
        GITHUB_TOKEN: ${{ github.token }}
